version: '3'

services:
  # Symfony app
  back:
    image: wiktorwz/notes_back:latest
    working_dir: /var/www/html/symfony
#    environment:
#      MONGODB_URL:
#      MONGODB_DB:
    ports:
      - 81:80

  # React app
  front:
    image: wiktorwz/notes_front:latest
    working_dir: /usr/share/nginx/html
    environment:
      BACKEND_SERVER: "http://localhost:81"
    ports:
      - 80:80

  # DataBase
  database:
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: databasee
#    volumes:
#      - database_volume:/data/db
#
#volumes:
#  database_volume:
