version: '3'

services:
  # Symfony app
  back:
    image: wiktorwz/notes_back:latest
    working_dir: /var/www/html/symfony
    ports:
      - 81:80

  # React app
  front:
    image: wiktorwz/notes_front:latest
    working_dir: /usr/share/nginx/html
    ports:
      - 80:80

  # DataBase
  database:
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
    volumes:
      - database_volume:/data/db

volumes:
  database_volume:
